#!/bin/bash
currentCu01=$(cat /home/coreApplication/current.log | grep cu01 | grep -v inspur | sort -k 3 | awk '{print $3}')
echo -e "=== $(cat /home/coreApplication/current.log | grep cu01 | awk '{sum += $5};END {print 72-sum}') core(s) available on cu01. ==="
cat /home/coreApplication/current.log | grep cu01 | grep -v inspur
cpusCu01=$(ssh cu01 "cpuAlert" | awk '{print $1}')
ssh cu01 "cpuAlert"
for i in $cpusCu01
do
    if [[ "$currentCu01" =~ "$i" ]]; then
        continue
    else
        oldDate=$(cat /home/coreApplication/application_history.log | grep $i | tail -n -1 | awk '{print $1,$2}')
        oldTime=$(date -d "$oldDate" +%s)
        nowTime=$(date +%s)
        nowSeconds=$[$nowTime-$oldTime]
        echo "!!! $i expired $[$nowSeconds/3600] hour(s) $[$nowSeconds%3600/60] minute(s)!!!"                                                                                     
    fi  
done
echo "++++++++++++++++"
currentCu02=$(cat /home/coreApplication/current.log | grep cu02 | grep -v inspur | sort -k 3 | awk '{print $3}')
echo -e "=== $(cat /home/coreApplication/current.log | grep cu02 | awk '{sum += $5};END {print 72-sum}') core(s) available on cu02. ==="
cat /home/coreApplication/current.log | grep cu02 | grep -v inspur
cpusCu02=$(ssh cu02 "cpuAlert" | awk '{print $1}')
ssh cu02 "cpuAlert"
for i in $cpusCu02
do
    if [[ "$currentCu02" =~ "$i" ]]; then
        continue
    else
        oldDate=$(cat /home/coreApplication/application_history.log | grep $i | tail -n -1 | awk '{print $1,$2}')
        oldTime=$(date -d "$oldDate" +%s)
        nowTime=$(date +%s)
        nowSeconds=$[$nowTime-$oldTime]
        echo "!!! $i expired $[$nowSeconds/3600] hour(s) $[$nowSeconds%3600/60] minute(s)!!!"
    fi  
done
echo "++++++++++++++++"
#echo "=== on cu01 ==="
#cat /home/coreApplication/current.log | grep cu01 | grep -v inspur | sort -k 3
#echo -e "=== $(cat /home/coreApplication/current.log | grep cu02 | awk '{sum += $5};END {print 72-sum}') core(s) available on cu01. ==="
#ssh cu01 "cpuAlert"
#echo "=== on cu02 ==="
#cat /home/coreApplication/current.log | grep cu02 | grep -v inspur | sort -k 3
#echo -e "=== $(cat /home/coreApplication/current.log | grep cu02 | awk '{sum += $5};END {print 72-sum}') core(s) available on cu02. ==="
#ssh cu02 "cpuAlert"
