#!/bin/bash
userPath="/data/$1"
if [[ ! -d "/data/$1" ]]; then
        sudo mkdir /data/$1
        sudo chown $1:students $userPath
        sudo chmod 700 $userPath
else
        echo "The path already exists!"
fi
