#!/bin/bash

if [ -z "$1" ]; then
    echo "Please enter the path or press '0' to exit."
    read -r path
    if [ "$path" = "0" ]; then
        exit 0
    else
        du -sh $path/*/ | sort -hr
    fi
else
    du -sh $1/*/ | sort -hr
fi