#!/bin/bash
i=${1-7} 
if [[ $2 != "" && $(lastlog -t $i | grep $2) =~ $2 ]]; then
        echo "User $(lastlog -t $i | grep $2 | awk '{print $1}') loginned in $i days."
        lastlog -t $i | grep $2
elif [[ $2 != "" ]]; then
        echo "User $2 NOT loginned in $i days."
else        
        echo "In last $i days, users below loginned:"                           
        lastlog -t $i | grep "[0-9]\{10\}"
fi
