#!/bin/bash

# 检查是否带有用户名参数
if [ $# -gt 0 ]; then
    username=$1
    # 在 /data 路径下创建以用户名命名的文件夹
    sudo mkdir -p /data/$username
    # 修改文件夹的所有者和所在群组
    sudo chown $username:students /data/$username
    # 赋予700权限
    sudo chmod 700 /data/$username
else
    # 提示用户输入用户名或输入0退出
    echo "Please enter username or press '0' to exit"
    read username
    if [ "$username" = "0" ]; then
        exit 0
    fi
    # 在 /data 路径下创建以输入的用户名命名的文件夹
    mkdir -p /data/$username
    # 修改文件夹的所有者和所在群组
    sudo chown $username:students /data/$username
    # 赋予700权限
    chmod 700 /data/$username
fi