#!/bin/bash
date
echo -e "USER \t \t %CPU"
top -n 1 -b | grep $1 | awk '{if($9!="0.0") print $2 "\t" $9}' | head -$2
echo "----------------"
echo "total cpu used: $(top -n 1 -b | grep $1 | awk '{if($9!="0.0") print $9}' | head -$2 | awk '{sum += $1};END {print sum}')"
