#!/bin/bash
cat /home/coreApplication/current.log /home/coreApplication/application_history.log | sort | uniq > /home/coreApplication/tmp.log
cp /home/coreApplication/tmp.log /home/coreApplication/application_history.log
rm /home/coreApplication/tmp.log
