#!/bin/bash
cu01=$((72-$(cat /home/coreApplication/current.log | grep cu01 | awk '{sum += $5};END {print sum}')))
cu02=$((72-$(cat /home/coreApplication/current.log | grep cu02 | awk '{sum += $5};END {print sum}')))

if (( $cu01 <= 0 ))  && (( $cu02 <= 0 )); then
        echo "There is no spare core now, please try again later."
        exit
elif (( $cu01 > 0 )) && (( $cu02 <= 0 )); then
        echo "Only cu01 has $cu01 spare core(s) now."
elif (( $cu01 <= 0 )) && (( $cu02 > 0 )); then
        echo "Only cu02 has $cu02 spare core(s) now."
else
        echo -e "cu01 has $cu01 spare core(s). \ncu02 has $cu02 spare core(s)."
fi

if [[ -n $(cat /home/coreApplication/current.log | awk '{print $3}' | grep $USER) ]]; then
        echo "Your last application will expire at $(cat /home/coreApplication/current.log | grep $USER | awk '{print $2 " on " $1}')."
        exit
fi

echo "=== Press Ctrl+C to exit this script. ==="
while true
do
        read -p "Please select node[cu01/cu02]:" node
        if [[ $node != "cu01" && $node != "cu02" ]]; then
                echo "Node name input error."
                continue
        fi
        read -p "please enter number of cores[default:10]:" coreNumber
        #read -p "please enter day(s) of using[default:3]:" daysExpire
        daysExpire=4
        if [[ $node == "cu01" ]]; then
                if (( $coreNumber <= $cu01 )); then
                        break
                else
                        echo "Number of cores on $node input error."
                fi
        elif [[ $node == "cu02" ]]; then
                if (( $coreNumber <= $cu02 )); then
                        break
                else
                        echo "Number of cores on $node input error."
                fi
        fi
done

echo -e "Account: \t$USER"
echo -e "Applied: \t$coreNumber cores"
echo -e "Expire on: \t$(date +"%Y-%m-%d %H:%M:%S" -d "-$daysExpire days ago")"
echo -e "$(date +"%Y-%m-%d %H:%M:%S" -d "-$daysExpire days ago") $USER \t$node \t$coreNumber" >> /home/coreApplication/current.log
